const specs = [
    {
        id: 1,
        title: "Taycan",
        emissions: "Electrical consumption combined (model range): 20.0 - 16.7 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
        acceleration: "4.8",
        kw: "300",
        ps: "408",
        speed: "143",
    },{
        id: 2,
          title: "Taycan 4S",
          emissions:"Electrical consumption combined (model range): 20.9 - 17.7 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration:"3.7",
          kw:"400",
          ps: "544",
          speed:"155",
    },{
        id:3,
        title: "Taycan Turbo",
        emissions:"Electrical consumption combined (model range): 20.5 - 18.0 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
        acceleration:"2.7",
        kw:"650",
        ps: "884",
        speed:"162",
    },{
        id:4,
          title: "Taycan Turbo S",
          emissions:"Electrical consumption combined (model range): 20.5 - 17.9 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration:"2.4",
          kw:"700",
          ps: "952",
          speed:"162",
    },{
        id:5,
             title: "Taycan Turbo GT with Weissach Package",
            price: "£ 186,300.00",
            emissions:"Electrical consumption combined (model range): 21.3 - 20.6 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
            acceleration:"2.2",
            kw:"760",
            ps: "1034",
            speed:"190",
    },{
        id: 6,
              title: "Taycan Turbo GT",
              emissions:"Electrical consumption combined (model range): 21.6 - 20.7 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
              acceleration:"2.3",
              kw:"760",
              ps: "1034",
              speed:"180",
    },{
        id:7,
        title: "Taycan 4 Cross Turismo",
        emissions:"Electrical consumption combined (model range): 22.0 - 18.7 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
        acceleration:"4.7",
        kw:"320",
        ps: "435",
        speed:"137",  
    },{
        id:8,
         title: "Taycan 4S Cross Turismo",
          emissions:"Electrical consumption combined (model range): 22.0 - 18.8 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration:"3.8",
          kw:"440",
          ps: "598",
          speed:"149",
    },{
        id:9,
          title: "Taycan Turbo Cross Turismo",
           emissions:"Electrical consumption combined (model range): 22.0 - 19.1 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration:"2.8",
          kw:"650",
          ps: "884",
          speed:"155",
    },{
        id:10,
          title: "Taycan Sport Turismo",
          emissions:"Electrical consumption combined (model range): 20.9 - 17.6 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration: "4.8",
          kw: "300",
          ps: "408",
          speed: "143",
    },{
        id:11,
          title: "Taycan 4S Sport Turismo",
          emissions:"Electrical consumption combined (model range): 21.8 - 18.5 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration: "3.7",
          kw: "544",
          ps: "400",
          speed: "155",
    },{
        id:12,
          title: "Taycan Turbo Sport Turismo",
          emissions:"Electrical consumption combined (model range): 21.6 - 18.8 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration: "2.7",
          kw: "650",
          ps: "884",
          speed: "162"
    },{
        id:13,
          title: "Taycan Turbo S Sport Turismo",
          emissions:"Electrical consumption combined (model range): 21.5 - 18.9 kWh/100 km, CO2 emissions combined* (model range): 0 g/km",
          acceleration: "2.4",
          kw: "700",
          ps: "952",
          speed: "162",
    },{
        id:14,
            title: "718 Cayman",
           emissions: "Fuel consumption combined* (model range): 29.1 - 31.7 mpg, CO2 emissions combined* (model range): 220 - 201 g/km",
            acceleration: "5.1",
            kw: "220",
            ps: "300",
            speed: "170",
    },{
        id:15,
        title: "718 Boxster",
        emissions: "Fuel consumption combined* (model range): 29.1 – 31.7 mpg, CO2 emissions combined* (model range): 220 – 201 g/km",
        acceleration: "5.1",
        kw: "220",
        ps: "300",
        speed: "170",
    },{
        id:16,
            title: "718 Cayman Style Edition",
            emissions: "Fuel consumption combined* (model range): 29.1 – 31.7 mpg, CO2 emissions combined* (model range): 220 – 201 g/km",
            acceleration: "5.1",
            kw: "220",
            ps: "300",
            speed: "170",
    },{
        id:17,
            title: "718 Boxster Style Edition",
           emissions: "Fuel consumption combined* (model range): 29.1 – 31.7 mpg, CO2 emissions combined* (model range): 220 – 203 g/km",
            acceleration: "5.1",
            kw: "220",
            ps: "300",
            speed: "171",
    },{
        id:18,
            title: "718 Cayman S",
            emissions: "Fuel consumption combined* (model range): 27.4 – 29.4 mpg, CO2 emissions combined* (model range): 235 – 217 g/km",
            acceleration: "4.6",
            kw: "257",
            ps: "350",
            speed: "177",
    },{
        id:19,
            title: "718 Cayman GTS 4.0",
            emissions: "Fuel consumption combined* (model range): 25.9 – 28.0 mpg, CO2 emissions combined* (model range): 247 – 230 g/km",
            acceleration: "4.5",
            kw: "294",
            ps: "400",
            speed: "182",
    },{
        id:20,
        title: "718 Boxster GTS 4.0",
        emissions: "Fuel consumption combined* (model range): 25.9 – 28.0 mpg, CO2 emissions combined* (model range): 247 – 230 g/km",
        acceleration: "4.5",
        kw: "294",
        ps: "400",
        speed: "182",
    },{
        id:21,
        title: "718 Cayman GT4 RS",
        emissions: "Fuel consumption combined* (model range): 21.4 mpg, CO2 emissions combined* (model range): 299 g/km",
        acceleration: "3.4",
        kw: "368",
        ps: "500",
        speed: "196",
    },{
        id:22,
        title: "718 Spyder RS",
        emissions: "Fuel consumption combined* (model range): 21.7 mpg, CO2 emissions combined* (model range): 294 g/km",
        acceleration: "3.4",
        kw: "368",
        ps: "500",
        speed: "191",
    },{
        id:23,
        title: "911 Carrera",
        emissions: "Fuel consumption combined* (model range): 26.2 – 27.4 mpg, CCO2 emissions combined* (model range): 245 – 233 g/km",
        acceleration: "4.2",
        kw: "0",
        ps: "385",
        speed: "182",
    },{
        id:24,
        title: "911 Carrera T",
        emissions: "Fuel consumption combined* (model range): 25.9 – 27.4 mpg, CO2 emissions combined* (model range): 247 – 233 g/km",
        acceleration: "4.5",
        kw: "0",
        ps: "385",
        speed: "181",
    },{
        id:25,
        title: "911 Carrera Cabriolet",
       emissions: "Fuel consumption combined* (model range): 26.2 – 27.2 mpg, CO2 emissions combined* (model range): 245 – 236 g/km",
        acceleration: "4.4",
        kw: "0",
        ps: "385",
        speed: "181",
    },{
        id:26,
        title: "911 Carrera 4",
        emissions: "Fuel consumption combined* (model range): 25.9 – 27.4 mpg, CO2 emissions combined* (model range): 247 – 234 g/km",
        acceleration: "4.2",
        kw: "0",
        ps: "385",
        speed: "181",
    },{
        id:27,
         title: "911 Carrera 4 Cabriolet",
       emissions: "Fuel consumption combined* (model range): 26.2 – 26.9 mpg, CO2 emissions combined* (model range): 246 – 238 g/km",
        acceleration: "4.4",
        kw: "0",
        ps: "385",
        speed: "180",
    },{
        id:28,
        title: "911 Carrera S",
        emissions: "Fuel consumption combined* (model range): 25.4 – 28.0 mpg, CO2 emissions combined* (model range): 251 – 229 g/km",
        acceleration: "3.7",
        kw: "0",
        ps: "450",
        speed: "191",
    },{
        id:29,
        title: "911 Carrera S Cabriolet",
        emissions: "Fuel consumption combined* (model range): 25.7 – 27.4 mpg, CO2 emissions combined* (model range): 250 – 233 g/km",
        acceleration: "3.9",
        kw: "0",
        ps: "450",
        speed: "190",
    },{
        id:30,
        title: "911 Carrera 4S",
        acceleration: "3.6",
        emissions: "Fuel consumption combined* (model range): 25.4 – 27.7 mpg, CO2 emissions combined* (model range): 253 – 231 g/km",
        acceleration: "3.6",
        kw: "0",
        ps: "450",
        speed: "190",
    },{
        id:31,
        title: "911 Carrera 4S Cabriolet",
        emissions: "Fuel consumption combined* (model range): 25.4 – 27.2 mpg, CO2 emissions combined* (model range): 252 – 235 g/km",
        acceleration: "3.8",
        kw: "0",
        ps: "450",
        speed: "189",
    },{
        id:32,
        title: "911 Carrera GTS",
        emissions: "Fuel consumption combined* (model range): 24.8 – 27.2 mpg, CO2 emissions combined* (model range): 258 – 236 g/km",
        acceleration: "3.4",
        kw: "0",
        ps: "480",
        speed: "193",
    },{
        id:33,
        title: "911 Carrera GTS Cabriolet",
        emissions: "Fuel consumption combined* (model range): 25.0 – 27.2 mpg, CO2 emissions combined* (model range): 256 – 239 g/km",
        acceleration: "3.6",
        kw: "0",
        ps: "480",
        speed: "192",
    },{
        id:34,
        title: "911 Carrera 4 GTS",
        emissions: "Fuel consumption combined* (model range): 24.8 – 26.6 mpg, CO2 emissions combined* (model range): 259 – 240 g/km",
        acceleration: "3.3",
        kw: "0",
        ps: "480",
        speed: "192",
    },{
        id:35,
        title: "911 Carrera 4 GTS Cabriolet",
        emissions: "Fuel consumption combined* (model range): 25.0 – 26.2 mpg, CO2 emissions combined* (model range): 256 – 244 g/km",
        acceleration: "3.5",
        kw: "0",
        ps: "480",
        speed: "191",
    },{
        id:36,
        title: "911 Edition 50 Years Posrche Design",
        emissions: "Fuel consumption combined* (model range): 25.0 – 26.2 mpg, CO2 emissions combined* (model range): 257 – 245 g/km",
        acceleration: "3.5",
        kw: "0",
        ps: "480",
        speed: "191",
    },{
        id:37,
        title: "911 Targa 4",
        emissions: "Fuel consumption combined* (model range): 25.4 – 27.2 mpg, CO2 emissions combined* (model range): 252 – 235 g/km",
        acceleration: "4.4",
        kw: "0",
        ps: "385",
        speed: "179",
    },{
        id:38,
        title: "911 Targa 4S",
        emissions: "Fuel consumption combined* (model range): 25.4 – 27.2 mpg, CO2 emissions combined* (model range): 252 – 235 g/km",
        acceleration: "3.8",
        kw: "0",
        ps: "450",
        speed: "189",
    },{
        id:39,
        title: "911 Targa 4 GTS",
        emissions: "Fuel consumption combined* (model range): 25.0 – 26.2 mpg, CO2 emissions combined* (model range): 257 – 245 g/km",
        acceleration: "3.5",
        kw: "0",
        ps: "480",
        speed: "191",
    },{
        id:40,
    title: "911 Turbo",
    emissions: "Fuel consumption combined* (model range): 23.0 – 23.5 mpg, CCO2 emissions combined* (model range): 279 – 271 g/km",
    acceleration: "2.8",
    kw: "0",
    ps: "580",
    speed: "199",
    },{
        id:41,
    title: "911 Turbo Cabriolet",
    emissions: "Fuel consumption combined* (model range): 22.6 – 23.3 mpg, CCO2 emissions combined* (model range): 284 – 275 g/km",
    acceleration: "2.9",
    kw: "0",
    ps: "580",
    speed: "199",
    },{
        id:42,
    title: "911 Turbo S",
    emissions: "Fuel consumption combined* (model range): 23.0 – 23.5 mpg, CCO2 emissions combined* (model range): 278 – 271 g/km",
    acceleration: "2.7",
    kw: "0",
    ps: "650",
    speed: "205",
    },{
        id:43,
    title: "911 Turbo S Cabriolet",
    emissions: "Fuel consumption combined* (model range): 22.6 – 23.3 mpg, CCO2 emissions combined* (model range): 284 – 275 g/km",
    acceleration: "2.8",
    kw: "0",
    ps: "650",
    speed: "205",
    },{ 
        id: 44,
        title: "911 Dakar",
        acceleration: "3.4",
        kw: "0",
        ps: "480",
        emissions: "Fuel consumption combined* (model range): 25.0 mpg, CO2 emissions combined* (model range): 256 g/km",
        speed: "149",
    },{
        id:45,
        title: "911 GT3",
        acceleration: "3.4",
        kw: "375",
        ps: "510",
        emissions: "Fuel consumption combined* (model range): 21.7 – 21.9 mpg, CO2 emissions combined* (model range): 294 – 293 g/km",
        speed: "198",
    },{
        id:46,
        title: "911 GT3 with Touring Package",
        acceleration: "3.9",
        kw: "375",
        ps: "510",
        emissions: "Fuel consumption combined* (model range): 21.9 mpg, CO2 emissions combined* (model range): 293 – 292 g/km",
        speed: "199",
    },{
        id:47,
      title: "911 GT3 RS",
      acceleration: "3.2",
      kw: "386",
      ps: "525",
      emissions: "Fuel consumption combined* (model range): 21.1 mpg, CO2 emissions combined* (model range): 305 g/km",
      speed: "184",
    },{
        id:48,
      title: "911 S/T",
      acceleration: "3.7",
      kw: "386",
      ps: "525",
      emissions: "Fuel consumption combined* (model range): 20.5 mpg, CO2 emissions combined* (model range): 313 g/km",
      speed: "186",
    }
]


export default specs;